#path to the godot-cpp SConstruct file
env = SConscript('../Libraries/godot-cpp/SConstruct')

#define include path for godot-cpp
env.Append(CPPPATH='src/')

# define library path for godot-cpp
# env.Append(LIBPATH='godot-cpp/bin')


# store all .cpp files in the src directory inside variable
src_files = env.Glob('src/*.cpp')

if env['platform'] == 'windows':
    # libpath is the name of the shared library, inside parent folder
    # {specifiction for platform} {extension of library .dll}
    # other stuff is mostly from godot-cpp SConstruct
    libpath = '../bin/libtest{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])
    shared_lib = env.SharedLibrary(libpath, src_files)
    Default(shared_lib)
elif env['platform'] == 'linux':
    libpath = '../bin/libtest{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])
    shared_lib = env.SharedLibrary(libpath, src_files)
    Default(shared_lib)
elif env['platform'] == 'osx':
    libpath = '../bin/libtest{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])
    shared_lib = env.SharedLibrary(libpath, src_files)
    Default(shared_lib)